#! /bin/sh

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config pointer_modifier 'mod1'
bspc config pointer_action1 'move'
bspc config pointer_action2 'resize_size'
bspc config pointer_action3 'resize_corner'

sxhkd &
hsetroot -fill ~/.wallpaper
compton -b
export QT_SCALE_FACTOR=1.7
xsetroot -cursor_name left_ptr &
$HOME/.config/lemonbar/lemonbar.sh | lemonbar -p -g x30 -f "Roboto Mono for Powerline:size=18" -f "FontAwesome:size=18" -u 3 -o -2| bash &
libinput-gestures &

